name: Automation
on:
  issue_comment:
    types: [created]

jobs:
  apply-clang-format:
    name: "Apply clang-format"
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'Auto clang-format')
    steps:
      - uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Gotcha'
            })
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master
      - name: Install clang-format-11
        run: |
          sudo apt-get install clang-format-11
      - name: Format the code
        env:
          BASE_REF: "${{ github.event.pull_request.base.ref }}"
        run: |
          files=$(
            git diff --name-only --diff-filter=r "$BASE_REF" HEAD \
            | grep -v dependencies/ \
            | grep -E '(\.h|\.cpp)'
          )
          clang-format-11 -i $files
      - name: Create a commit
        run: |
          git set author.name '${{ github.event.comment.author.name }} via automation'
          git set author.email '${{ github.event.comment.author.email }}'
          git commit -a \
            -m "Automated clang-format" \
            -m "Files changed: $files" \
            -m "See PR #${{ github.event.pull_request.number }}"
