name: Automation
on:
  issue_comment:
    types: [created]

jobs:
  apply-clang-format:
    name: "Apply clang-format"
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'Auto clang-format')
    steps:
      - uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Gotcha'
            })
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install clang-format-11
        run: |
          sudo apt-get install clang-format-11
      - name: Format the code
        run: |
          find -name dependencies -prune -o \
            \( -name '*.h' -o -name '*.cpp' \) \
            -print \
            -exec clang-format-11 -i '{}' +
      - name: Commit and push
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'actions@github.com>'
          # Only try to commit if clang-format changed something
          if git diff --quiet ; then
            git commit -a \
              -m "Automated clang-format" \
              -m "Files changed: $files" \
              -m "See PR #${{ github.event.pull_request.number }}"
          fi
          git push "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}" \
            "HEAD:${GITHUB_REF_NAME}"
